// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

/**
 * <pre>
 * Цифровые входы
 * </pre>
 *
 * Protobuf type {@code SensDinsFlags}
 */
public final class SensDinsFlags extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SensDinsFlags)
    SensDinsFlagsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SensDinsFlags.class.getName());
  }
  // Use SensDinsFlags.newBuilder() to construct.
  private SensDinsFlags(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SensDinsFlags() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensDinsFlags_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensDinsFlags_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.libs.SensDinsFlags.class, org.example.libs.SensDinsFlags.Builder.class);
  }

  public static final int SENS_NUM_FIELD_NUMBER = 1;
  private int sensNum_ = 0;
  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  @java.lang.Override
  public int getSensNum() {
    return sensNum_;
  }

  public static final int DEVICE_FIELD_NUMBER = 2;
  private int device_ = 0;
  /**
   * <pre>
   * Входы прибора (каждый бит соответствует своему входу)
   * </pre>
   *
   * <code>uint32 device = 2;</code>
   * @return The device.
   */
  @java.lang.Override
  public int getDevice() {
    return device_;
  }

  public static final int EXTERNAL_FIELD_NUMBER = 3;
  private int external_ = 0;
  /**
   * <pre>
   * Внешние входы (каждый бит соответствует своему входу)
   * </pre>
   *
   * <code>uint32 external = 3;</code>
   * @return The external.
   */
  @java.lang.Override
  public int getExternal() {
    return external_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensNum_ != 0) {
      output.writeUInt32(1, sensNum_);
    }
    if (device_ != 0) {
      output.writeUInt32(2, device_);
    }
    if (external_ != 0) {
      output.writeUInt32(3, external_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, sensNum_);
    }
    if (device_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, device_);
    }
    if (external_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, external_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.libs.SensDinsFlags)) {
      return super.equals(obj);
    }
    org.example.libs.SensDinsFlags other = (org.example.libs.SensDinsFlags) obj;

    if (getSensNum()
        != other.getSensNum()) return false;
    if (getDevice()
        != other.getDevice()) return false;
    if (getExternal()
        != other.getExternal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENS_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getSensNum();
    hash = (37 * hash) + DEVICE_FIELD_NUMBER;
    hash = (53 * hash) + getDevice();
    hash = (37 * hash) + EXTERNAL_FIELD_NUMBER;
    hash = (53 * hash) + getExternal();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.libs.SensDinsFlags parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensDinsFlags parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensDinsFlags parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.libs.SensDinsFlags parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.libs.SensDinsFlags parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensDinsFlags parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.libs.SensDinsFlags prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Цифровые входы
   * </pre>
   *
   * Protobuf type {@code SensDinsFlags}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensDinsFlags)
      org.example.libs.SensDinsFlagsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensDinsFlags_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensDinsFlags_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.libs.SensDinsFlags.class, org.example.libs.SensDinsFlags.Builder.class);
    }

    // Construct using org.example.libs.SensDinsFlags.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensNum_ = 0;
      device_ = 0;
      external_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensDinsFlags_descriptor;
    }

    @java.lang.Override
    public org.example.libs.SensDinsFlags getDefaultInstanceForType() {
      return org.example.libs.SensDinsFlags.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.libs.SensDinsFlags build() {
      org.example.libs.SensDinsFlags result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.libs.SensDinsFlags buildPartial() {
      org.example.libs.SensDinsFlags result = new org.example.libs.SensDinsFlags(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.libs.SensDinsFlags result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensNum_ = sensNum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.device_ = device_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.external_ = external_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.libs.SensDinsFlags) {
        return mergeFrom((org.example.libs.SensDinsFlags)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.libs.SensDinsFlags other) {
      if (other == org.example.libs.SensDinsFlags.getDefaultInstance()) return this;
      if (other.getSensNum() != 0) {
        setSensNum(other.getSensNum());
      }
      if (other.getDevice() != 0) {
        setDevice(other.getDevice());
      }
      if (other.getExternal() != 0) {
        setExternal(other.getExternal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensNum_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              device_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              external_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sensNum_ ;
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return The sensNum.
     */
    @java.lang.Override
    public int getSensNum() {
      return sensNum_;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @param value The sensNum to set.
     * @return This builder for chaining.
     */
    public Builder setSensNum(int value) {

      sensNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sensNum_ = 0;
      onChanged();
      return this;
    }

    private int device_ ;
    /**
     * <pre>
     * Входы прибора (каждый бит соответствует своему входу)
     * </pre>
     *
     * <code>uint32 device = 2;</code>
     * @return The device.
     */
    @java.lang.Override
    public int getDevice() {
      return device_;
    }
    /**
     * <pre>
     * Входы прибора (каждый бит соответствует своему входу)
     * </pre>
     *
     * <code>uint32 device = 2;</code>
     * @param value The device to set.
     * @return This builder for chaining.
     */
    public Builder setDevice(int value) {

      device_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Входы прибора (каждый бит соответствует своему входу)
     * </pre>
     *
     * <code>uint32 device = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevice() {
      bitField0_ = (bitField0_ & ~0x00000002);
      device_ = 0;
      onChanged();
      return this;
    }

    private int external_ ;
    /**
     * <pre>
     * Внешние входы (каждый бит соответствует своему входу)
     * </pre>
     *
     * <code>uint32 external = 3;</code>
     * @return The external.
     */
    @java.lang.Override
    public int getExternal() {
      return external_;
    }
    /**
     * <pre>
     * Внешние входы (каждый бит соответствует своему входу)
     * </pre>
     *
     * <code>uint32 external = 3;</code>
     * @param value The external to set.
     * @return This builder for chaining.
     */
    public Builder setExternal(int value) {

      external_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Внешние входы (каждый бит соответствует своему входу)
     * </pre>
     *
     * <code>uint32 external = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearExternal() {
      bitField0_ = (bitField0_ & ~0x00000004);
      external_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SensDinsFlags)
  }

  // @@protoc_insertion_point(class_scope:SensDinsFlags)
  private static final org.example.libs.SensDinsFlags DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.libs.SensDinsFlags();
  }

  public static org.example.libs.SensDinsFlags getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensDinsFlags>
      PARSER = new com.google.protobuf.AbstractParser<SensDinsFlags>() {
    @java.lang.Override
    public SensDinsFlags parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensDinsFlags> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensDinsFlags> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.libs.SensDinsFlags getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

