// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensFuelLevelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensFuelLevel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Значение датчика
   * </pre>
   *
   * <code>float value = 2;</code>
   * @return The value.
   */
  float getValue();

  /**
   * <pre>
   * Значение датчика в условных единицах
   * </pre>
   *
   * <code>uint32 parrots = 3;</code>
   * @return The parrots.
   */
  int getParrots();

  /**
   * <pre>
   * Единица измерения для поля value (1 - литры, 2 - миллилитры)
   * </pre>
   *
   * <code>uint32 unit = 4;</code>
   * @return The unit.
   */
  int getUnit();

  /**
   * <pre>
   * Температура датчика
   * </pre>
   *
   * <code>uint32 t = 5;</code>
   * @return The t.
   */
  int getT();

  /**
   * <pre>
   * Статус датчика
   * </pre>
   *
   * <code>uint32 status = 6;</code>
   * @return The status.
   */
  int getStatus();
}
