// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

/**
 * <pre>
 * Расширение CAN-лога
 * </pre>
 *
 * Protobuf type {@code SensCanLogTmpDataExt}
 */
public final class SensCanLogTmpDataExt extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SensCanLogTmpDataExt)
    SensCanLogTmpDataExtOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SensCanLogTmpDataExt.class.getName());
  }
  // Use SensCanLogTmpDataExt.newBuilder() to construct.
  private SensCanLogTmpDataExt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SensCanLogTmpDataExt() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensCanLogTmpDataExt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensCanLogTmpDataExt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.libs.SensCanLogTmpDataExt.class, org.example.libs.SensCanLogTmpDataExt.Builder.class);
  }

  public static final int SENS_NUM_FIELD_NUMBER = 1;
  private int sensNum_ = 0;
  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  @java.lang.Override
  public int getSensNum() {
    return sensNum_;
  }

  public static final int FLAGS_HIGH_FIELD_NUMBER = 2;
  private int flagsHigh_ = 0;
  /**
   * <pre>
   * Флаги механизмов
   * </pre>
   *
   * <code>uint32 flags_high = 2;</code>
   * @return The flagsHigh.
   */
  @java.lang.Override
  public int getFlagsHigh() {
    return flagsHigh_;
  }

  public static final int FLAGS_LOW_FIELD_NUMBER = 3;
  private int flagsLow_ = 0;
  /**
   * <pre>
   * Флаги механизмов
   * </pre>
   *
   * <code>uint32 flags_low = 3;</code>
   * @return The flagsLow.
   */
  @java.lang.Override
  public int getFlagsLow() {
    return flagsLow_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensNum_ != 0) {
      output.writeUInt32(1, sensNum_);
    }
    if (flagsHigh_ != 0) {
      output.writeUInt32(2, flagsHigh_);
    }
    if (flagsLow_ != 0) {
      output.writeUInt32(3, flagsLow_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, sensNum_);
    }
    if (flagsHigh_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, flagsHigh_);
    }
    if (flagsLow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, flagsLow_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.libs.SensCanLogTmpDataExt)) {
      return super.equals(obj);
    }
    org.example.libs.SensCanLogTmpDataExt other = (org.example.libs.SensCanLogTmpDataExt) obj;

    if (getSensNum()
        != other.getSensNum()) return false;
    if (getFlagsHigh()
        != other.getFlagsHigh()) return false;
    if (getFlagsLow()
        != other.getFlagsLow()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENS_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getSensNum();
    hash = (37 * hash) + FLAGS_HIGH_FIELD_NUMBER;
    hash = (53 * hash) + getFlagsHigh();
    hash = (37 * hash) + FLAGS_LOW_FIELD_NUMBER;
    hash = (53 * hash) + getFlagsLow();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.libs.SensCanLogTmpDataExt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.libs.SensCanLogTmpDataExt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensCanLogTmpDataExt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.libs.SensCanLogTmpDataExt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Расширение CAN-лога
   * </pre>
   *
   * Protobuf type {@code SensCanLogTmpDataExt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensCanLogTmpDataExt)
      org.example.libs.SensCanLogTmpDataExtOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensCanLogTmpDataExt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensCanLogTmpDataExt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.libs.SensCanLogTmpDataExt.class, org.example.libs.SensCanLogTmpDataExt.Builder.class);
    }

    // Construct using org.example.libs.SensCanLogTmpDataExt.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensNum_ = 0;
      flagsHigh_ = 0;
      flagsLow_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensCanLogTmpDataExt_descriptor;
    }

    @java.lang.Override
    public org.example.libs.SensCanLogTmpDataExt getDefaultInstanceForType() {
      return org.example.libs.SensCanLogTmpDataExt.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.libs.SensCanLogTmpDataExt build() {
      org.example.libs.SensCanLogTmpDataExt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.libs.SensCanLogTmpDataExt buildPartial() {
      org.example.libs.SensCanLogTmpDataExt result = new org.example.libs.SensCanLogTmpDataExt(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.libs.SensCanLogTmpDataExt result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensNum_ = sensNum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.flagsHigh_ = flagsHigh_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.flagsLow_ = flagsLow_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.libs.SensCanLogTmpDataExt) {
        return mergeFrom((org.example.libs.SensCanLogTmpDataExt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.libs.SensCanLogTmpDataExt other) {
      if (other == org.example.libs.SensCanLogTmpDataExt.getDefaultInstance()) return this;
      if (other.getSensNum() != 0) {
        setSensNum(other.getSensNum());
      }
      if (other.getFlagsHigh() != 0) {
        setFlagsHigh(other.getFlagsHigh());
      }
      if (other.getFlagsLow() != 0) {
        setFlagsLow(other.getFlagsLow());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensNum_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              flagsHigh_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              flagsLow_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sensNum_ ;
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return The sensNum.
     */
    @java.lang.Override
    public int getSensNum() {
      return sensNum_;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @param value The sensNum to set.
     * @return This builder for chaining.
     */
    public Builder setSensNum(int value) {

      sensNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sensNum_ = 0;
      onChanged();
      return this;
    }

    private int flagsHigh_ ;
    /**
     * <pre>
     * Флаги механизмов
     * </pre>
     *
     * <code>uint32 flags_high = 2;</code>
     * @return The flagsHigh.
     */
    @java.lang.Override
    public int getFlagsHigh() {
      return flagsHigh_;
    }
    /**
     * <pre>
     * Флаги механизмов
     * </pre>
     *
     * <code>uint32 flags_high = 2;</code>
     * @param value The flagsHigh to set.
     * @return This builder for chaining.
     */
    public Builder setFlagsHigh(int value) {

      flagsHigh_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Флаги механизмов
     * </pre>
     *
     * <code>uint32 flags_high = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlagsHigh() {
      bitField0_ = (bitField0_ & ~0x00000002);
      flagsHigh_ = 0;
      onChanged();
      return this;
    }

    private int flagsLow_ ;
    /**
     * <pre>
     * Флаги механизмов
     * </pre>
     *
     * <code>uint32 flags_low = 3;</code>
     * @return The flagsLow.
     */
    @java.lang.Override
    public int getFlagsLow() {
      return flagsLow_;
    }
    /**
     * <pre>
     * Флаги механизмов
     * </pre>
     *
     * <code>uint32 flags_low = 3;</code>
     * @param value The flagsLow to set.
     * @return This builder for chaining.
     */
    public Builder setFlagsLow(int value) {

      flagsLow_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Флаги механизмов
     * </pre>
     *
     * <code>uint32 flags_low = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlagsLow() {
      bitField0_ = (bitField0_ & ~0x00000004);
      flagsLow_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SensCanLogTmpDataExt)
  }

  // @@protoc_insertion_point(class_scope:SensCanLogTmpDataExt)
  private static final org.example.libs.SensCanLogTmpDataExt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.libs.SensCanLogTmpDataExt();
  }

  public static org.example.libs.SensCanLogTmpDataExt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensCanLogTmpDataExt>
      PARSER = new com.google.protobuf.AbstractParser<SensCanLogTmpDataExt>() {
    @java.lang.Override
    public SensCanLogTmpDataExt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensCanLogTmpDataExt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensCanLogTmpDataExt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.libs.SensCanLogTmpDataExt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

