// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensAccelerometerDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensAccelerometerData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Буфер с данными
   * </pre>
   *
   * <code>bytes buf = 2;</code>
   * @return The buf.
   */
  com.google.protobuf.ByteString getBuf();

  /**
   * <pre>
   * UTC время формирования первой отметки в буфере
   * </pre>
   *
   * <code>uint32 atm = 3;</code>
   * @return The atm.
   */
  int getAtm();

  /**
   * <pre>
   * Частота следования отметок в ГЦ деленная на 10
   * </pre>
   *
   * <code>uint32 frequency = 4;</code>
   * @return The frequency.
   */
  int getFrequency();

  /**
   * <pre>
   * Диапазон измерений акселерометра умноженный на 10
   * </pre>
   *
   * <code>uint32 range = 5;</code>
   * @return The range.
   */
  int getRange();

  /**
   * <pre>
   * Тип кодирования отметок (0 - 8-ми битовые значения со знаком,
   * </pre>
   *
   * <code>uint32 format = 6;</code>
   * @return The format.
   */
  int getFormat();

  /**
   * <pre>
   * 1 - 16-ти битовые значения со знаком, 2 - 32-х битовые значения со знаком, 3 - в формате ASN1 PER )
   * </pre>
   *
   * <code>uint32 zlib = 7;</code>
   * @return The zlib.
   */
  int getZlib();
}
