// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

/**
 * <pre>
 * Информация о базовых станциях GSM
 * </pre>
 *
 * Protobuf type {@code SensGsmCellMonitoring}
 */
public final class SensGsmCellMonitoring extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SensGsmCellMonitoring)
    SensGsmCellMonitoringOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SensGsmCellMonitoring.class.getName());
  }
  // Use SensGsmCellMonitoring.newBuilder() to construct.
  private SensGsmCellMonitoring(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SensGsmCellMonitoring() {
    lac_ = com.google.protobuf.ByteString.EMPTY;
    cid_ = com.google.protobuf.ByteString.EMPTY;
    rssi_ = com.google.protobuf.ByteString.EMPTY;
    timeAdv_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensGsmCellMonitoring_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensGsmCellMonitoring_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.libs.SensGsmCellMonitoring.class, org.example.libs.SensGsmCellMonitoring.Builder.class);
  }

  public static final int SENS_NUM_FIELD_NUMBER = 1;
  private int sensNum_ = 0;
  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  @java.lang.Override
  public int getSensNum() {
    return sensNum_;
  }

  public static final int LAC_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString lac_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Код локальной зоны
   * </pre>
   *
   * <code>bytes lac = 4;</code>
   * @return The lac.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLac() {
    return lac_;
  }

  public static final int CID_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString cid_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Идентификатор соты
   * </pre>
   *
   * <code>bytes cid = 5;</code>
   * @return The cid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCid() {
    return cid_;
  }

  public static final int RSSI_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString rssi_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Уровень принимаемого по данному каналу радиосигнала на входе в приёмник телефона
   * </pre>
   *
   * <code>bytes rssi = 6;</code>
   * @return The rssi.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRssi() {
    return rssi_;
  }

  public static final int TIME_ADV_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString timeAdv_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Параметр компенсации времени прохождения сигнала от телефона до БС
   * </pre>
   *
   * <code>bytes time_adv = 7;</code>
   * @return The timeAdv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTimeAdv() {
    return timeAdv_;
  }

  public static final int MCC_FIELD_NUMBER = 2;
  private int mcc_ = 0;
  /**
   * <pre>
   * Код страны
   * </pre>
   *
   * <code>uint32 mcc = 2;</code>
   * @return The mcc.
   */
  @java.lang.Override
  public int getMcc() {
    return mcc_;
  }

  public static final int MNC_FIELD_NUMBER = 3;
  private int mnc_ = 0;
  /**
   * <pre>
   * Код сотовой сети
   * </pre>
   *
   * <code>uint32 mnc = 3;</code>
   * @return The mnc.
   */
  @java.lang.Override
  public int getMnc() {
    return mnc_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensNum_ != 0) {
      output.writeUInt32(1, sensNum_);
    }
    if (mcc_ != 0) {
      output.writeUInt32(2, mcc_);
    }
    if (mnc_ != 0) {
      output.writeUInt32(3, mnc_);
    }
    if (!lac_.isEmpty()) {
      output.writeBytes(4, lac_);
    }
    if (!cid_.isEmpty()) {
      output.writeBytes(5, cid_);
    }
    if (!rssi_.isEmpty()) {
      output.writeBytes(6, rssi_);
    }
    if (!timeAdv_.isEmpty()) {
      output.writeBytes(7, timeAdv_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, sensNum_);
    }
    if (mcc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, mcc_);
    }
    if (mnc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, mnc_);
    }
    if (!lac_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, lac_);
    }
    if (!cid_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, cid_);
    }
    if (!rssi_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, rssi_);
    }
    if (!timeAdv_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, timeAdv_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.libs.SensGsmCellMonitoring)) {
      return super.equals(obj);
    }
    org.example.libs.SensGsmCellMonitoring other = (org.example.libs.SensGsmCellMonitoring) obj;

    if (getSensNum()
        != other.getSensNum()) return false;
    if (!getLac()
        .equals(other.getLac())) return false;
    if (!getCid()
        .equals(other.getCid())) return false;
    if (!getRssi()
        .equals(other.getRssi())) return false;
    if (!getTimeAdv()
        .equals(other.getTimeAdv())) return false;
    if (getMcc()
        != other.getMcc()) return false;
    if (getMnc()
        != other.getMnc()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENS_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getSensNum();
    hash = (37 * hash) + LAC_FIELD_NUMBER;
    hash = (53 * hash) + getLac().hashCode();
    hash = (37 * hash) + CID_FIELD_NUMBER;
    hash = (53 * hash) + getCid().hashCode();
    hash = (37 * hash) + RSSI_FIELD_NUMBER;
    hash = (53 * hash) + getRssi().hashCode();
    hash = (37 * hash) + TIME_ADV_FIELD_NUMBER;
    hash = (53 * hash) + getTimeAdv().hashCode();
    hash = (37 * hash) + MCC_FIELD_NUMBER;
    hash = (53 * hash) + getMcc();
    hash = (37 * hash) + MNC_FIELD_NUMBER;
    hash = (53 * hash) + getMnc();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.libs.SensGsmCellMonitoring parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.libs.SensGsmCellMonitoring parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensGsmCellMonitoring parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.libs.SensGsmCellMonitoring prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Информация о базовых станциях GSM
   * </pre>
   *
   * Protobuf type {@code SensGsmCellMonitoring}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensGsmCellMonitoring)
      org.example.libs.SensGsmCellMonitoringOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensGsmCellMonitoring_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensGsmCellMonitoring_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.libs.SensGsmCellMonitoring.class, org.example.libs.SensGsmCellMonitoring.Builder.class);
    }

    // Construct using org.example.libs.SensGsmCellMonitoring.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensNum_ = 0;
      lac_ = com.google.protobuf.ByteString.EMPTY;
      cid_ = com.google.protobuf.ByteString.EMPTY;
      rssi_ = com.google.protobuf.ByteString.EMPTY;
      timeAdv_ = com.google.protobuf.ByteString.EMPTY;
      mcc_ = 0;
      mnc_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensGsmCellMonitoring_descriptor;
    }

    @java.lang.Override
    public org.example.libs.SensGsmCellMonitoring getDefaultInstanceForType() {
      return org.example.libs.SensGsmCellMonitoring.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.libs.SensGsmCellMonitoring build() {
      org.example.libs.SensGsmCellMonitoring result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.libs.SensGsmCellMonitoring buildPartial() {
      org.example.libs.SensGsmCellMonitoring result = new org.example.libs.SensGsmCellMonitoring(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.libs.SensGsmCellMonitoring result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensNum_ = sensNum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.lac_ = lac_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cid_ = cid_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.rssi_ = rssi_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timeAdv_ = timeAdv_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.mcc_ = mcc_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.mnc_ = mnc_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.libs.SensGsmCellMonitoring) {
        return mergeFrom((org.example.libs.SensGsmCellMonitoring)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.libs.SensGsmCellMonitoring other) {
      if (other == org.example.libs.SensGsmCellMonitoring.getDefaultInstance()) return this;
      if (other.getSensNum() != 0) {
        setSensNum(other.getSensNum());
      }
      if (!other.getLac().isEmpty()) {
        setLac(other.getLac());
      }
      if (!other.getCid().isEmpty()) {
        setCid(other.getCid());
      }
      if (!other.getRssi().isEmpty()) {
        setRssi(other.getRssi());
      }
      if (!other.getTimeAdv().isEmpty()) {
        setTimeAdv(other.getTimeAdv());
      }
      if (other.getMcc() != 0) {
        setMcc(other.getMcc());
      }
      if (other.getMnc() != 0) {
        setMnc(other.getMnc());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensNum_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              mcc_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 16
            case 24: {
              mnc_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 24
            case 34: {
              lac_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            case 42: {
              cid_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 42
            case 50: {
              rssi_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 50
            case 58: {
              timeAdv_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sensNum_ ;
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return The sensNum.
     */
    @java.lang.Override
    public int getSensNum() {
      return sensNum_;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @param value The sensNum to set.
     * @return This builder for chaining.
     */
    public Builder setSensNum(int value) {

      sensNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sensNum_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString lac_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Код локальной зоны
     * </pre>
     *
     * <code>bytes lac = 4;</code>
     * @return The lac.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLac() {
      return lac_;
    }
    /**
     * <pre>
     * Код локальной зоны
     * </pre>
     *
     * <code>bytes lac = 4;</code>
     * @param value The lac to set.
     * @return This builder for chaining.
     */
    public Builder setLac(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      lac_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Код локальной зоны
     * </pre>
     *
     * <code>bytes lac = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLac() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lac_ = getDefaultInstance().getLac();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString cid_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Идентификатор соты
     * </pre>
     *
     * <code>bytes cid = 5;</code>
     * @return The cid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCid() {
      return cid_;
    }
    /**
     * <pre>
     * Идентификатор соты
     * </pre>
     *
     * <code>bytes cid = 5;</code>
     * @param value The cid to set.
     * @return This builder for chaining.
     */
    public Builder setCid(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      cid_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор соты
     * </pre>
     *
     * <code>bytes cid = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cid_ = getDefaultInstance().getCid();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rssi_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Уровень принимаемого по данному каналу радиосигнала на входе в приёмник телефона
     * </pre>
     *
     * <code>bytes rssi = 6;</code>
     * @return The rssi.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRssi() {
      return rssi_;
    }
    /**
     * <pre>
     * Уровень принимаемого по данному каналу радиосигнала на входе в приёмник телефона
     * </pre>
     *
     * <code>bytes rssi = 6;</code>
     * @param value The rssi to set.
     * @return This builder for chaining.
     */
    public Builder setRssi(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      rssi_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Уровень принимаемого по данному каналу радиосигнала на входе в приёмник телефона
     * </pre>
     *
     * <code>bytes rssi = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRssi() {
      bitField0_ = (bitField0_ & ~0x00000008);
      rssi_ = getDefaultInstance().getRssi();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString timeAdv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Параметр компенсации времени прохождения сигнала от телефона до БС
     * </pre>
     *
     * <code>bytes time_adv = 7;</code>
     * @return The timeAdv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTimeAdv() {
      return timeAdv_;
    }
    /**
     * <pre>
     * Параметр компенсации времени прохождения сигнала от телефона до БС
     * </pre>
     *
     * <code>bytes time_adv = 7;</code>
     * @param value The timeAdv to set.
     * @return This builder for chaining.
     */
    public Builder setTimeAdv(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      timeAdv_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Параметр компенсации времени прохождения сигнала от телефона до БС
     * </pre>
     *
     * <code>bytes time_adv = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeAdv() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timeAdv_ = getDefaultInstance().getTimeAdv();
      onChanged();
      return this;
    }

    private int mcc_ ;
    /**
     * <pre>
     * Код страны
     * </pre>
     *
     * <code>uint32 mcc = 2;</code>
     * @return The mcc.
     */
    @java.lang.Override
    public int getMcc() {
      return mcc_;
    }
    /**
     * <pre>
     * Код страны
     * </pre>
     *
     * <code>uint32 mcc = 2;</code>
     * @param value The mcc to set.
     * @return This builder for chaining.
     */
    public Builder setMcc(int value) {

      mcc_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Код страны
     * </pre>
     *
     * <code>uint32 mcc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMcc() {
      bitField0_ = (bitField0_ & ~0x00000020);
      mcc_ = 0;
      onChanged();
      return this;
    }

    private int mnc_ ;
    /**
     * <pre>
     * Код сотовой сети
     * </pre>
     *
     * <code>uint32 mnc = 3;</code>
     * @return The mnc.
     */
    @java.lang.Override
    public int getMnc() {
      return mnc_;
    }
    /**
     * <pre>
     * Код сотовой сети
     * </pre>
     *
     * <code>uint32 mnc = 3;</code>
     * @param value The mnc to set.
     * @return This builder for chaining.
     */
    public Builder setMnc(int value) {

      mnc_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Код сотовой сети
     * </pre>
     *
     * <code>uint32 mnc = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMnc() {
      bitField0_ = (bitField0_ & ~0x00000040);
      mnc_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SensGsmCellMonitoring)
  }

  // @@protoc_insertion_point(class_scope:SensGsmCellMonitoring)
  private static final org.example.libs.SensGsmCellMonitoring DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.libs.SensGsmCellMonitoring();
  }

  public static org.example.libs.SensGsmCellMonitoring getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensGsmCellMonitoring>
      PARSER = new com.google.protobuf.AbstractParser<SensGsmCellMonitoring>() {
    @java.lang.Override
    public SensGsmCellMonitoring parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensGsmCellMonitoring> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensGsmCellMonitoring> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.libs.SensGsmCellMonitoring getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

