// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

/**
 * <pre>
 * Статистика хранилища
 * </pre>
 *
 * Protobuf type {@code SensStorInfo}
 */
public final class SensStorInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SensStorInfo)
    SensStorInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SensStorInfo.class.getName());
  }
  // Use SensStorInfo.newBuilder() to construct.
  private SensStorInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SensStorInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensStorInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensStorInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.libs.SensStorInfo.class, org.example.libs.SensStorInfo.Builder.class);
  }

  public static final int SENS_NUM_FIELD_NUMBER = 1;
  private int sensNum_ = 0;
  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  @java.lang.Override
  public int getSensNum() {
    return sensNum_;
  }

  public static final int ID_MAX_FIELD_NUMBER = 2;
  private int idMax_ = 0;
  /**
   * <pre>
   * Идентификатор самой новой отметки
   * </pre>
   *
   * <code>uint32 id_max = 2;</code>
   * @return The idMax.
   */
  @java.lang.Override
  public int getIdMax() {
    return idMax_;
  }

  public static final int ID_MIN_FIELD_NUMBER = 3;
  private int idMin_ = 0;
  /**
   * <pre>
   * Идентификатор самой старой отметки
   * </pre>
   *
   * <code>uint32 id_min = 3;</code>
   * @return The idMin.
   */
  @java.lang.Override
  public int getIdMin() {
    return idMin_;
  }

  public static final int TM_OLDEST_FIELD_NUMBER = 4;
  private int tmOldest_ = 0;
  /**
   * <pre>
   * Время создания самой старой отметки
   * </pre>
   *
   * <code>uint32 tm_oldest = 4;</code>
   * @return The tmOldest.
   */
  @java.lang.Override
  public int getTmOldest() {
    return tmOldest_;
  }

  public static final int TM_OLDEST_UNACK_FIELD_NUMBER = 5;
  private int tmOldestUnack_ = 0;
  /**
   * <pre>
   * Время создания самой старой отметки, которая не подтверждена
   * </pre>
   *
   * <code>uint32 tm_oldest_unack = 5;</code>
   * @return The tmOldestUnack.
   */
  @java.lang.Override
  public int getTmOldestUnack() {
    return tmOldestUnack_;
  }

  public static final int CNT_UNACK_FIELD_NUMBER = 6;
  private int cntUnack_ = 0;
  /**
   * <pre>
   * Количество неподтвержденных отметок
   * </pre>
   *
   * <code>uint32 cnt_unack = 6;</code>
   * @return The cntUnack.
   */
  @java.lang.Override
  public int getCntUnack() {
    return cntUnack_;
  }

  public static final int CNT_UNACK_LOSTED_FIELD_NUMBER = 7;
  private int cntUnackLosted_ = 0;
  /**
   * <pre>
   * Количество потерянных неподтвержденных отметок
   * </pre>
   *
   * <code>uint32 cnt_unack_losted = 7;</code>
   * @return The cntUnackLosted.
   */
  @java.lang.Override
  public int getCntUnackLosted() {
    return cntUnackLosted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensNum_ != 0) {
      output.writeUInt32(1, sensNum_);
    }
    if (idMax_ != 0) {
      output.writeUInt32(2, idMax_);
    }
    if (idMin_ != 0) {
      output.writeUInt32(3, idMin_);
    }
    if (tmOldest_ != 0) {
      output.writeUInt32(4, tmOldest_);
    }
    if (tmOldestUnack_ != 0) {
      output.writeUInt32(5, tmOldestUnack_);
    }
    if (cntUnack_ != 0) {
      output.writeUInt32(6, cntUnack_);
    }
    if (cntUnackLosted_ != 0) {
      output.writeUInt32(7, cntUnackLosted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, sensNum_);
    }
    if (idMax_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, idMax_);
    }
    if (idMin_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, idMin_);
    }
    if (tmOldest_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, tmOldest_);
    }
    if (tmOldestUnack_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, tmOldestUnack_);
    }
    if (cntUnack_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, cntUnack_);
    }
    if (cntUnackLosted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(7, cntUnackLosted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.libs.SensStorInfo)) {
      return super.equals(obj);
    }
    org.example.libs.SensStorInfo other = (org.example.libs.SensStorInfo) obj;

    if (getSensNum()
        != other.getSensNum()) return false;
    if (getIdMax()
        != other.getIdMax()) return false;
    if (getIdMin()
        != other.getIdMin()) return false;
    if (getTmOldest()
        != other.getTmOldest()) return false;
    if (getTmOldestUnack()
        != other.getTmOldestUnack()) return false;
    if (getCntUnack()
        != other.getCntUnack()) return false;
    if (getCntUnackLosted()
        != other.getCntUnackLosted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENS_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getSensNum();
    hash = (37 * hash) + ID_MAX_FIELD_NUMBER;
    hash = (53 * hash) + getIdMax();
    hash = (37 * hash) + ID_MIN_FIELD_NUMBER;
    hash = (53 * hash) + getIdMin();
    hash = (37 * hash) + TM_OLDEST_FIELD_NUMBER;
    hash = (53 * hash) + getTmOldest();
    hash = (37 * hash) + TM_OLDEST_UNACK_FIELD_NUMBER;
    hash = (53 * hash) + getTmOldestUnack();
    hash = (37 * hash) + CNT_UNACK_FIELD_NUMBER;
    hash = (53 * hash) + getCntUnack();
    hash = (37 * hash) + CNT_UNACK_LOSTED_FIELD_NUMBER;
    hash = (53 * hash) + getCntUnackLosted();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.libs.SensStorInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensStorInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensStorInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.libs.SensStorInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.libs.SensStorInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensStorInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.libs.SensStorInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Статистика хранилища
   * </pre>
   *
   * Protobuf type {@code SensStorInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensStorInfo)
      org.example.libs.SensStorInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensStorInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensStorInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.libs.SensStorInfo.class, org.example.libs.SensStorInfo.Builder.class);
    }

    // Construct using org.example.libs.SensStorInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensNum_ = 0;
      idMax_ = 0;
      idMin_ = 0;
      tmOldest_ = 0;
      tmOldestUnack_ = 0;
      cntUnack_ = 0;
      cntUnackLosted_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensStorInfo_descriptor;
    }

    @java.lang.Override
    public org.example.libs.SensStorInfo getDefaultInstanceForType() {
      return org.example.libs.SensStorInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.libs.SensStorInfo build() {
      org.example.libs.SensStorInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.libs.SensStorInfo buildPartial() {
      org.example.libs.SensStorInfo result = new org.example.libs.SensStorInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.libs.SensStorInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensNum_ = sensNum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idMax_ = idMax_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.idMin_ = idMin_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tmOldest_ = tmOldest_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tmOldestUnack_ = tmOldestUnack_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.cntUnack_ = cntUnack_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.cntUnackLosted_ = cntUnackLosted_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.libs.SensStorInfo) {
        return mergeFrom((org.example.libs.SensStorInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.libs.SensStorInfo other) {
      if (other == org.example.libs.SensStorInfo.getDefaultInstance()) return this;
      if (other.getSensNum() != 0) {
        setSensNum(other.getSensNum());
      }
      if (other.getIdMax() != 0) {
        setIdMax(other.getIdMax());
      }
      if (other.getIdMin() != 0) {
        setIdMin(other.getIdMin());
      }
      if (other.getTmOldest() != 0) {
        setTmOldest(other.getTmOldest());
      }
      if (other.getTmOldestUnack() != 0) {
        setTmOldestUnack(other.getTmOldestUnack());
      }
      if (other.getCntUnack() != 0) {
        setCntUnack(other.getCntUnack());
      }
      if (other.getCntUnackLosted() != 0) {
        setCntUnackLosted(other.getCntUnackLosted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensNum_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              idMax_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              idMin_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              tmOldest_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              tmOldestUnack_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              cntUnack_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              cntUnackLosted_ = input.readUInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sensNum_ ;
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return The sensNum.
     */
    @java.lang.Override
    public int getSensNum() {
      return sensNum_;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @param value The sensNum to set.
     * @return This builder for chaining.
     */
    public Builder setSensNum(int value) {

      sensNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sensNum_ = 0;
      onChanged();
      return this;
    }

    private int idMax_ ;
    /**
     * <pre>
     * Идентификатор самой новой отметки
     * </pre>
     *
     * <code>uint32 id_max = 2;</code>
     * @return The idMax.
     */
    @java.lang.Override
    public int getIdMax() {
      return idMax_;
    }
    /**
     * <pre>
     * Идентификатор самой новой отметки
     * </pre>
     *
     * <code>uint32 id_max = 2;</code>
     * @param value The idMax to set.
     * @return This builder for chaining.
     */
    public Builder setIdMax(int value) {

      idMax_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор самой новой отметки
     * </pre>
     *
     * <code>uint32 id_max = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdMax() {
      bitField0_ = (bitField0_ & ~0x00000002);
      idMax_ = 0;
      onChanged();
      return this;
    }

    private int idMin_ ;
    /**
     * <pre>
     * Идентификатор самой старой отметки
     * </pre>
     *
     * <code>uint32 id_min = 3;</code>
     * @return The idMin.
     */
    @java.lang.Override
    public int getIdMin() {
      return idMin_;
    }
    /**
     * <pre>
     * Идентификатор самой старой отметки
     * </pre>
     *
     * <code>uint32 id_min = 3;</code>
     * @param value The idMin to set.
     * @return This builder for chaining.
     */
    public Builder setIdMin(int value) {

      idMin_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор самой старой отметки
     * </pre>
     *
     * <code>uint32 id_min = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdMin() {
      bitField0_ = (bitField0_ & ~0x00000004);
      idMin_ = 0;
      onChanged();
      return this;
    }

    private int tmOldest_ ;
    /**
     * <pre>
     * Время создания самой старой отметки
     * </pre>
     *
     * <code>uint32 tm_oldest = 4;</code>
     * @return The tmOldest.
     */
    @java.lang.Override
    public int getTmOldest() {
      return tmOldest_;
    }
    /**
     * <pre>
     * Время создания самой старой отметки
     * </pre>
     *
     * <code>uint32 tm_oldest = 4;</code>
     * @param value The tmOldest to set.
     * @return This builder for chaining.
     */
    public Builder setTmOldest(int value) {

      tmOldest_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Время создания самой старой отметки
     * </pre>
     *
     * <code>uint32 tm_oldest = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTmOldest() {
      bitField0_ = (bitField0_ & ~0x00000008);
      tmOldest_ = 0;
      onChanged();
      return this;
    }

    private int tmOldestUnack_ ;
    /**
     * <pre>
     * Время создания самой старой отметки, которая не подтверждена
     * </pre>
     *
     * <code>uint32 tm_oldest_unack = 5;</code>
     * @return The tmOldestUnack.
     */
    @java.lang.Override
    public int getTmOldestUnack() {
      return tmOldestUnack_;
    }
    /**
     * <pre>
     * Время создания самой старой отметки, которая не подтверждена
     * </pre>
     *
     * <code>uint32 tm_oldest_unack = 5;</code>
     * @param value The tmOldestUnack to set.
     * @return This builder for chaining.
     */
    public Builder setTmOldestUnack(int value) {

      tmOldestUnack_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Время создания самой старой отметки, которая не подтверждена
     * </pre>
     *
     * <code>uint32 tm_oldest_unack = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTmOldestUnack() {
      bitField0_ = (bitField0_ & ~0x00000010);
      tmOldestUnack_ = 0;
      onChanged();
      return this;
    }

    private int cntUnack_ ;
    /**
     * <pre>
     * Количество неподтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_unack = 6;</code>
     * @return The cntUnack.
     */
    @java.lang.Override
    public int getCntUnack() {
      return cntUnack_;
    }
    /**
     * <pre>
     * Количество неподтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_unack = 6;</code>
     * @param value The cntUnack to set.
     * @return This builder for chaining.
     */
    public Builder setCntUnack(int value) {

      cntUnack_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество неподтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_unack = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCntUnack() {
      bitField0_ = (bitField0_ & ~0x00000020);
      cntUnack_ = 0;
      onChanged();
      return this;
    }

    private int cntUnackLosted_ ;
    /**
     * <pre>
     * Количество потерянных неподтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_unack_losted = 7;</code>
     * @return The cntUnackLosted.
     */
    @java.lang.Override
    public int getCntUnackLosted() {
      return cntUnackLosted_;
    }
    /**
     * <pre>
     * Количество потерянных неподтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_unack_losted = 7;</code>
     * @param value The cntUnackLosted to set.
     * @return This builder for chaining.
     */
    public Builder setCntUnackLosted(int value) {

      cntUnackLosted_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество потерянных неподтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_unack_losted = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCntUnackLosted() {
      bitField0_ = (bitField0_ & ~0x00000040);
      cntUnackLosted_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SensStorInfo)
  }

  // @@protoc_insertion_point(class_scope:SensStorInfo)
  private static final org.example.libs.SensStorInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.libs.SensStorInfo();
  }

  public static org.example.libs.SensStorInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensStorInfo>
      PARSER = new com.google.protobuf.AbstractParser<SensStorInfo>() {
    @java.lang.Override
    public SensStorInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensStorInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensStorInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.libs.SensStorInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

