// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

/**
 * <pre>
 * Статистика трекера
 * </pre>
 *
 * Protobuf type {@code SensTrackerInfo}
 */
public final class SensTrackerInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SensTrackerInfo)
    SensTrackerInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SensTrackerInfo.class.getName());
  }
  // Use SensTrackerInfo.newBuilder() to construct.
  private SensTrackerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SensTrackerInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensTrackerInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.libs.StorageRecordOuterClass.internal_static_SensTrackerInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.libs.SensTrackerInfo.class, org.example.libs.SensTrackerInfo.Builder.class);
  }

  public static final int SENS_NUM_FIELD_NUMBER = 1;
  private int sensNum_ = 0;
  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  @java.lang.Override
  public int getSensNum() {
    return sensNum_;
  }

  public static final int CNT_ACK_FIELD_NUMBER = 2;
  private int cntAck_ = 0;
  /**
   * <pre>
   * Количество подтвержденных отметок
   * </pre>
   *
   * <code>uint32 cnt_ack = 2;</code>
   * @return The cntAck.
   */
  @java.lang.Override
  public int getCntAck() {
    return cntAck_;
  }

  public static final int CNT_ACK_REALTIME_FIELD_NUMBER = 3;
  private int cntAckRealtime_ = 0;
  /**
   * <pre>
   * Количество подтвержденных отметок в качестве realtime
   * </pre>
   *
   * <code>uint32 cnt_ack_realtime = 3;</code>
   * @return The cntAckRealtime.
   */
  @java.lang.Override
  public int getCntAckRealtime() {
    return cntAckRealtime_;
  }

  public static final int CNT_NOACK_FIELD_NUMBER = 4;
  private int cntNoack_ = 0;
  /**
   * <pre>
   * Количество отметок, которых не получилось отправить
   * </pre>
   *
   * <code>uint32 cnt_noack = 4;</code>
   * @return The cntNoack.
   */
  @java.lang.Override
  public int getCntNoack() {
    return cntNoack_;
  }

  public static final int CNT_CONNECT_FIELD_NUMBER = 5;
  private int cntConnect_ = 0;
  /**
   * <pre>
   * Количество соединений с сервером
   * </pre>
   *
   * <code>uint32 cnt_connect = 5;</code>
   * @return The cntConnect.
   */
  @java.lang.Override
  public int getCntConnect() {
    return cntConnect_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensNum_ != 0) {
      output.writeUInt32(1, sensNum_);
    }
    if (cntAck_ != 0) {
      output.writeUInt32(2, cntAck_);
    }
    if (cntAckRealtime_ != 0) {
      output.writeUInt32(3, cntAckRealtime_);
    }
    if (cntNoack_ != 0) {
      output.writeUInt32(4, cntNoack_);
    }
    if (cntConnect_ != 0) {
      output.writeUInt32(5, cntConnect_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, sensNum_);
    }
    if (cntAck_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, cntAck_);
    }
    if (cntAckRealtime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, cntAckRealtime_);
    }
    if (cntNoack_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, cntNoack_);
    }
    if (cntConnect_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, cntConnect_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.libs.SensTrackerInfo)) {
      return super.equals(obj);
    }
    org.example.libs.SensTrackerInfo other = (org.example.libs.SensTrackerInfo) obj;

    if (getSensNum()
        != other.getSensNum()) return false;
    if (getCntAck()
        != other.getCntAck()) return false;
    if (getCntAckRealtime()
        != other.getCntAckRealtime()) return false;
    if (getCntNoack()
        != other.getCntNoack()) return false;
    if (getCntConnect()
        != other.getCntConnect()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENS_NUM_FIELD_NUMBER;
    hash = (53 * hash) + getSensNum();
    hash = (37 * hash) + CNT_ACK_FIELD_NUMBER;
    hash = (53 * hash) + getCntAck();
    hash = (37 * hash) + CNT_ACK_REALTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCntAckRealtime();
    hash = (37 * hash) + CNT_NOACK_FIELD_NUMBER;
    hash = (53 * hash) + getCntNoack();
    hash = (37 * hash) + CNT_CONNECT_FIELD_NUMBER;
    hash = (53 * hash) + getCntConnect();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.libs.SensTrackerInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.libs.SensTrackerInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.libs.SensTrackerInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.libs.SensTrackerInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.libs.SensTrackerInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Статистика трекера
   * </pre>
   *
   * Protobuf type {@code SensTrackerInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensTrackerInfo)
      org.example.libs.SensTrackerInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensTrackerInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensTrackerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.libs.SensTrackerInfo.class, org.example.libs.SensTrackerInfo.Builder.class);
    }

    // Construct using org.example.libs.SensTrackerInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sensNum_ = 0;
      cntAck_ = 0;
      cntAckRealtime_ = 0;
      cntNoack_ = 0;
      cntConnect_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.libs.StorageRecordOuterClass.internal_static_SensTrackerInfo_descriptor;
    }

    @java.lang.Override
    public org.example.libs.SensTrackerInfo getDefaultInstanceForType() {
      return org.example.libs.SensTrackerInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.libs.SensTrackerInfo build() {
      org.example.libs.SensTrackerInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.libs.SensTrackerInfo buildPartial() {
      org.example.libs.SensTrackerInfo result = new org.example.libs.SensTrackerInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.libs.SensTrackerInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sensNum_ = sensNum_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cntAck_ = cntAck_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cntAckRealtime_ = cntAckRealtime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cntNoack_ = cntNoack_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.cntConnect_ = cntConnect_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.libs.SensTrackerInfo) {
        return mergeFrom((org.example.libs.SensTrackerInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.libs.SensTrackerInfo other) {
      if (other == org.example.libs.SensTrackerInfo.getDefaultInstance()) return this;
      if (other.getSensNum() != 0) {
        setSensNum(other.getSensNum());
      }
      if (other.getCntAck() != 0) {
        setCntAck(other.getCntAck());
      }
      if (other.getCntAckRealtime() != 0) {
        setCntAckRealtime(other.getCntAckRealtime());
      }
      if (other.getCntNoack() != 0) {
        setCntNoack(other.getCntNoack());
      }
      if (other.getCntConnect() != 0) {
        setCntConnect(other.getCntConnect());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensNum_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              cntAck_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              cntAckRealtime_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              cntNoack_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              cntConnect_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int sensNum_ ;
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return The sensNum.
     */
    @java.lang.Override
    public int getSensNum() {
      return sensNum_;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @param value The sensNum to set.
     * @return This builder for chaining.
     */
    public Builder setSensNum(int value) {

      sensNum_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер датчика
     * </pre>
     *
     * <code>uint32 sens_num = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensNum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sensNum_ = 0;
      onChanged();
      return this;
    }

    private int cntAck_ ;
    /**
     * <pre>
     * Количество подтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_ack = 2;</code>
     * @return The cntAck.
     */
    @java.lang.Override
    public int getCntAck() {
      return cntAck_;
    }
    /**
     * <pre>
     * Количество подтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_ack = 2;</code>
     * @param value The cntAck to set.
     * @return This builder for chaining.
     */
    public Builder setCntAck(int value) {

      cntAck_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество подтвержденных отметок
     * </pre>
     *
     * <code>uint32 cnt_ack = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCntAck() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cntAck_ = 0;
      onChanged();
      return this;
    }

    private int cntAckRealtime_ ;
    /**
     * <pre>
     * Количество подтвержденных отметок в качестве realtime
     * </pre>
     *
     * <code>uint32 cnt_ack_realtime = 3;</code>
     * @return The cntAckRealtime.
     */
    @java.lang.Override
    public int getCntAckRealtime() {
      return cntAckRealtime_;
    }
    /**
     * <pre>
     * Количество подтвержденных отметок в качестве realtime
     * </pre>
     *
     * <code>uint32 cnt_ack_realtime = 3;</code>
     * @param value The cntAckRealtime to set.
     * @return This builder for chaining.
     */
    public Builder setCntAckRealtime(int value) {

      cntAckRealtime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество подтвержденных отметок в качестве realtime
     * </pre>
     *
     * <code>uint32 cnt_ack_realtime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCntAckRealtime() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cntAckRealtime_ = 0;
      onChanged();
      return this;
    }

    private int cntNoack_ ;
    /**
     * <pre>
     * Количество отметок, которых не получилось отправить
     * </pre>
     *
     * <code>uint32 cnt_noack = 4;</code>
     * @return The cntNoack.
     */
    @java.lang.Override
    public int getCntNoack() {
      return cntNoack_;
    }
    /**
     * <pre>
     * Количество отметок, которых не получилось отправить
     * </pre>
     *
     * <code>uint32 cnt_noack = 4;</code>
     * @param value The cntNoack to set.
     * @return This builder for chaining.
     */
    public Builder setCntNoack(int value) {

      cntNoack_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество отметок, которых не получилось отправить
     * </pre>
     *
     * <code>uint32 cnt_noack = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCntNoack() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cntNoack_ = 0;
      onChanged();
      return this;
    }

    private int cntConnect_ ;
    /**
     * <pre>
     * Количество соединений с сервером
     * </pre>
     *
     * <code>uint32 cnt_connect = 5;</code>
     * @return The cntConnect.
     */
    @java.lang.Override
    public int getCntConnect() {
      return cntConnect_;
    }
    /**
     * <pre>
     * Количество соединений с сервером
     * </pre>
     *
     * <code>uint32 cnt_connect = 5;</code>
     * @param value The cntConnect to set.
     * @return This builder for chaining.
     */
    public Builder setCntConnect(int value) {

      cntConnect_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Количество соединений с сервером
     * </pre>
     *
     * <code>uint32 cnt_connect = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCntConnect() {
      bitField0_ = (bitField0_ & ~0x00000010);
      cntConnect_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:SensTrackerInfo)
  }

  // @@protoc_insertion_point(class_scope:SensTrackerInfo)
  private static final org.example.libs.SensTrackerInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.libs.SensTrackerInfo();
  }

  public static org.example.libs.SensTrackerInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensTrackerInfo>
      PARSER = new com.google.protobuf.AbstractParser<SensTrackerInfo>() {
    @java.lang.Override
    public SensTrackerInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensTrackerInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensTrackerInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.libs.SensTrackerInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

