// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensNdNavDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensNdNavData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Долгота (в формате МНД ЭРА ГЛОНАСС)
   * </pre>
   *
   * <code>sfixed32 longitude = 2;</code>
   * @return The longitude.
   */
  int getLongitude();

  /**
   * <pre>
   * Широта (в формате МНД ЭРА ГЛОНАСС)
   * </pre>
   *
   * <code>sfixed32 latitude = 3;</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <pre>
   * Высота, м
   * </pre>
   *
   * <code>uint32 altitude = 4;</code>
   * @return The altitude.
   */
  int getAltitude();

  /**
   * <pre>
   * Скорость, км/ч
   * </pre>
   *
   * <code>uint32 speed = 5;</code>
   * @return The speed.
   */
  int getSpeed();

  /**
   * <pre>
   * Курс (угол)
   * </pre>
   *
   * <code>uint32 course = 6;</code>
   * @return The course.
   */
  int getCourse();

  /**
   * <pre>
   * Количество спутников
   * </pre>
   *
   * <code>uint32 sat_count = 7;</code>
   * @return The satCount.
   */
  int getSatCount();

  /**
   * <pre>
   * Погрешность позиционирования
   * </pre>
   *
   * <code>uint32 pdop = 8;</code>
   * @return The pdop.
   */
  int getPdop();

  /**
   * <pre>
   * Трэк, м
   * </pre>
   *
   * <code>uint32 track = 9;</code>
   * @return The track.
   */
  int getTrack();

  /**
   * <pre>
   * Одометр, м
   * </pre>
   *
   * <code>uint32 odometer = 10;</code>
   * @return The odometer.
   */
  int getOdometer();
}
