// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensTermoDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensTermoData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Статус датчика (0 - исправен, 1 - нет ответа, 2 - неисправность)
   * </pre>
   *
   * <code>uint32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   * Температура
   * </pre>
   *
   * <code>sint32 temperature = 3;</code>
   * @return The temperature.
   */
  int getTemperature();
}
