// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensAinAinValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensAinAinValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Значение в милливольтах
   * </pre>
   *
   * <code>uint32 mv = 2;</code>
   * @return The mv.
   */
  int getMv();
}
