// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensDoutsFlagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensDoutsFlags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Выходы прибора (каждый бит соответствует своему выходу)
   * </pre>
   *
   * <code>uint32 device = 2;</code>
   * @return The device.
   */
  int getDevice();

  /**
   * <pre>
   * Внешние выходы (каждый бит соответствует своему выходу)
   * </pre>
   *
   * <code>uint32 external = 3;</code>
   * @return The external.
   */
  int getExternal();
}
