// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensDinsFlagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensDinsFlags)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Входы прибора (каждый бит соответствует своему входу)
   * </pre>
   *
   * <code>uint32 device = 2;</code>
   * @return The device.
   */
  int getDevice();

  /**
   * <pre>
   * Внешние входы (каждый бит соответствует своему входу)
   * </pre>
   *
   * <code>uint32 external = 3;</code>
   * @return The external.
   */
  int getExternal();
}
