// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensCrashDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensCrashData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Сила удара
   * </pre>
   *
   * <code>uint32 energy = 2;</code>
   * @return The energy.
   */
  int getEnergy();

  /**
   * <pre>
   * Признак переворота
   * </pre>
   *
   * <code>bool is_overturned = 3;</code>
   * @return The isOverturned.
   */
  boolean getIsOverturned();
}
