// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensCanLogTmpDataExtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensCanLogTmpDataExt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Флаги механизмов
   * </pre>
   *
   * <code>uint32 flags_high = 2;</code>
   * @return The flagsHigh.
   */
  int getFlagsHigh();

  /**
   * <pre>
   * Флаги механизмов
   * </pre>
   *
   * <code>uint32 flags_low = 3;</code>
   * @return The flagsLow.
   */
  int getFlagsLow();
}
