// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage_record.proto
// Protobuf Java Version: 4.30.2

package org.example.libs;

public interface SensStorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensStorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Номер датчика
   * </pre>
   *
   * <code>uint32 sens_num = 1;</code>
   * @return The sensNum.
   */
  int getSensNum();

  /**
   * <pre>
   * Идентификатор самой новой отметки
   * </pre>
   *
   * <code>uint32 id_max = 2;</code>
   * @return The idMax.
   */
  int getIdMax();

  /**
   * <pre>
   * Идентификатор самой старой отметки
   * </pre>
   *
   * <code>uint32 id_min = 3;</code>
   * @return The idMin.
   */
  int getIdMin();

  /**
   * <pre>
   * Время создания самой старой отметки
   * </pre>
   *
   * <code>uint32 tm_oldest = 4;</code>
   * @return The tmOldest.
   */
  int getTmOldest();

  /**
   * <pre>
   * Время создания самой старой отметки, которая не подтверждена
   * </pre>
   *
   * <code>uint32 tm_oldest_unack = 5;</code>
   * @return The tmOldestUnack.
   */
  int getTmOldestUnack();

  /**
   * <pre>
   * Количество неподтвержденных отметок
   * </pre>
   *
   * <code>uint32 cnt_unack = 6;</code>
   * @return The cntUnack.
   */
  int getCntUnack();

  /**
   * <pre>
   * Количество потерянных неподтвержденных отметок
   * </pre>
   *
   * <code>uint32 cnt_unack_losted = 7;</code>
   * @return The cntUnackLosted.
   */
  int getCntUnackLosted();
}
